
title: H2 Hire
desctiption: London based IT recruitment agency - run by experienced senior IT consultants!
url: https://www.h2hire.tk/
permalink: ':title/'

markdown: kramdown
baseurl: "/"
full-version: "https://www.h2hire.tk/"

sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-155731655-2

# Comments
disqus-shortname: h2hire

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token: a30ca44662ae99226e6a5c2b8431ed53

include: [_pages]
version: 0.8

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
